=== netwave8888/JavaScriptUnleashed/Chapter27/Listing27-03.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
   elementFormDefault = "qualified">
  <xsd:element name = "book">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref = "details"/>
        <xsd:element ref = "available"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name = "details">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref = "title"/>
        <xsd:element ref = "edition"/>
        <xsd:element ref = "publisher"/>
        <xsd:element ref = "authorList"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name = "title" type = "xsd:string"/>
  <xsd:element name = "edition" type = "xsd:string"/>
  <xsd:element name = "publisher" type = "xsd:string"/>
  <xsd:element name = "authorList">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref = "author" maxOccurs = "unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name = "author" type = "xsd:string"/>
  <xsd:element name = "available" type = "xsd:string"/>
</xsd:schema>

=== netwave8888/JavaScriptUnleashed/Chapter27/Listing27-04.xml
<?xml version = "1.0" encoding = "utf-8"?>
<book xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "Listing27-03.xsd">  
  <details>    
    <title>JavaScript Unleashed</title>    
    <edition>4th</edition>    
    <publisher>Sams</publisher>    
    <authorList>      
      <author>R. Allen Wyke</author>      
      <author>Jason D. Gilliam</author>    
    </authorList>  
  </details>  
  <available>2002</available>
</book>
